### ISSUE TITLE
Package is invalid error

### ISSUE THREAD

**Issue by SubhrajyotiSen** [tijmenennik/DynamicUA#1]
I dragged the file on edge://extensions in Edge.
Got the following error
<img width="367" alt="Screenshot 2019-05-29 at 2 16 00 AM" src="https://user-images.githubusercontent.com/12984845/58511189-f02d2700-81b7-11e9-9900-4102952fe538.png">

I have "Developer mode" and "Allow extensions from other stores" enabled

**Comment by tijmenennik** [comment]
Thanks for reporting the issue, a new installation process is now described inside the readme file.
